import '../data/models/currency_model.dart';


const currenciesList = [
  CurrencyModel(
    fullName: "US Dollar",
    shortName: "USD",
    symbol: "\$",
    image: "assets/icons/currencies-icons/icons8-us-dollar-circled-90.png",
  ),
  CurrencyModel(
    fullName: "Euro",
    shortName: "EUR",
    symbol: "€",
    image: "assets/icons/currencies-icons/icons8-euro-90.png",
  ),
  CurrencyModel(
    fullName: "Pound Sterling",
    shortName: "GBP",
    symbol: "£",
    image: "assets/icons/currencies-icons/icons8-british-pound-96.png",
  ),
  CurrencyModel(
    fullName: "Australian Dollar",
    shortName: "AUD",
    symbol: "\$",
    image: "assets/icons/countries-flag/australia.png",
  ),
  CurrencyModel(
    fullName: "Brazilian Real",
    shortName: "BRL",
    symbol: "R\$",
    image: "assets/icons/countries-flag/brazil.png",
  ),
  CurrencyModel(
    fullName: "Canadian Dollar",
    shortName: "CAD",
    symbol: "\$",
    image: "assets/icons/countries-flag/canada.png",
  ),
  CurrencyModel(
    fullName: "Swiss Franc",
    shortName: "CHF",
    symbol: "Fr",
    image: "assets/icons/countries-flag/switzerland.png",
  ),
  CurrencyModel(
    fullName: "Chilean Peso",
    shortName: "CLP",
    symbol: "\$",
    image: "assets/icons/countries-flag/chile.png",
  ),
  CurrencyModel(
    fullName: "Chinese Yuan",
    shortName: "CNY",
    symbol: "¥",
    image: "assets/icons/countries-flag/china.png",
  ),
  CurrencyModel(
    fullName: "Czech Koruna",
    shortName: "CZK",
    symbol: "Kč",
    image: "assets/icons/countries-flag/czech-republic.png",
  ),
  CurrencyModel(
    fullName: "Danish Krone",
    shortName: "DKK",
    symbol: "KR",
    image: "assets/icons/countries-flag/denmark.png",
  ),
  CurrencyModel(
    fullName: "Hong Kong Dollar",
    shortName: "HKD",
    symbol: "\$",
    image: "assets/icons/countries-flag/hong-kong.png",
  ),
  CurrencyModel(
    fullName: "Hungarian Forint",
    shortName: "HUF",
    symbol: "Ft",
    image: "assets/icons/countries-flag/hungary.png",
  ),
  CurrencyModel(
    fullName: "Indonesian Rupiah",
    shortName: "IDR",
    symbol: "Rp",
    image: "assets/icons/countries-flag/indonesia.png",
  ),
  CurrencyModel(
    fullName: "Israeli New Shekel",
    shortName: "ILS",
    symbol: "₪",
    image: "assets/icons/countries-flag/israel.png",
  ),
  CurrencyModel(
    fullName: "Indian Rupee",
    shortName: "INR",
    symbol: "₹",
    image: "assets/icons/countries-flag/india.png",
  ),
  CurrencyModel(
    fullName: "Japanese Yen",
    shortName: "JPY",
    symbol: "¥",
    image: "assets/icons/countries-flag/japan.png",
  ),
  CurrencyModel(
    fullName: "South Korean Won",
    shortName: "KRW",
    symbol: "₩",
    image: "assets/icons/countries-flag/south-korea.png",
  ),
  CurrencyModel(
    fullName: "Mexican Peso",
    shortName: "MXN",
    symbol: "\$",
    image: "assets/icons/countries-flag/mexican-flag.png",
  ),
  CurrencyModel(
    fullName: "Malaysian Ringgit",
    shortName: "MYR",
    symbol: "RM",
    image: "assets/icons/countries-flag/malaysia.png",
  ),
  CurrencyModel(
    fullName: "Norwegian Krone",
    shortName: "NOK",
    symbol: "kr",
    image: "assets/icons/countries-flag/norway.png",
  ),
  CurrencyModel(
    fullName: "New Zealand Dollar",
    shortName: "NZD",
    symbol: "\$",
    image: "assets/icons/countries-flag/new-zeland.png",
  ),
  CurrencyModel(
    fullName: "Philippine Peso",
    shortName: "PHP",
    symbol: "₱",
    image: "assets/icons/countries-flag/philippines.png",
  ),
  CurrencyModel(
    fullName: "Pakistani Rupee",
    shortName: "PKR",
    symbol: "₨",
    image: "assets/icons/countries-flag/pakistan.png",
  ),
  CurrencyModel(
    fullName: "Polish Złoty",
    shortName: "PLN",
    symbol: "zł",
    image: "assets/icons/countries-flag/poland.png",
  ),
  CurrencyModel(
    fullName: "Russian Ruble",
    shortName: "RUB",
    symbol: "₽",
    image: "assets/icons/countries-flag/russia.png",
  ),
  CurrencyModel(
    fullName: "Swedish Krona",
    shortName: "SEK",
    symbol: "kr",
    image: "assets/icons/countries-flag/russia.png",
  ),
  CurrencyModel(
    fullName: "Singapore Dollar",
    shortName: "SGD",
    symbol: "S\$",
    image: "assets/icons/countries-flag/singapore.png",
  ),
  CurrencyModel(
    fullName: "Thai Baht",
    shortName: "THB",
    symbol: "฿",
    image: "assets/icons/countries-flag/thailand.png",
  ),
  CurrencyModel(
    fullName: "Turkish Lira",
    shortName: "TRY",
    symbol: "₺",
    image: "assets/icons/countries-flag/turkey.png",
  ),
  CurrencyModel(
    fullName: "New Taiwan Dollar",
    shortName: "TWD",
    symbol: "NT\$",
    image: "assets/icons/countries-flag/taiwan.png",
  ),
  CurrencyModel(
    fullName: "South African Rand",
    shortName: "ZAR",
    symbol: "R",
    image: "assets/icons/countries-flag/south-africa.png",
  ),
  CurrencyModel(
    fullName: "Vietnamese Dong",
    shortName: "VND",
    symbol: "₫",
    image: "assets/icons/countries-flag/vietnam.png",
  ),
  CurrencyModel(
    fullName: "Argentine Peso",
    shortName: "ARS",
    symbol: "ARS",
    image: "assets/icons/countries-flag/argentina.png",
  ),
  CurrencyModel(
    fullName: "Ukrainian Hryvnia",
    shortName: "UAH",
    symbol: "UAH",
    image: "assets/icons/countries-flag/ukraine.png",
  ),
  CurrencyModel(
    fullName: "Nigerian Naira",
    shortName: "NGN",
    symbol: "NGN",
    image: "assets/icons/countries-flag/nigeria.png",
  ),
  CurrencyModel(
    fullName: "U. A. E. Dirham",
    shortName: "AED",
    symbol: "AED",
    image: "assets/icons/countries-flag/united-arab-emirates.png",
  ),
  CurrencyModel(
    fullName: "Saudi Riyal",
    shortName: "SAR",
    symbol: "SAR",
    image: "assets/icons/countries-flag/saudi-arabia.png",
  ),
  CurrencyModel(
    fullName: "Bangladeshi Taka",
    shortName: "BDT",
    symbol: "BDT",
    image: "assets/icons/countries-flag/bangladesh.png",
  ),
];
