// Mocks generated by Mockito 5.1.0 from annotations
// in crypto_trends/test/features/coinList/presenter/bloc/coin_list_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:crypto_trends/errors/failures.dart' as _i6;
import 'package:crypto_trends/features/coinList/domain/entities/coin.dart'
    as _i7;
import 'package:crypto_trends/features/coinList/domain/repositories/get_coin_list_repository.dart'
    as _i2;
import 'package:crypto_trends/features/coinList/domain/usecases/get_coin_list.dart'
    as _i4;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCoinListRepository_0 extends _i1.Fake
    implements _i2.CoinListRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetRemoteCoinList].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRemoteCoinList extends _i1.Mock implements _i4.GetRemoteCoinList {
  MockGetRemoteCoinList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CoinListRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeCoinListRepository_0()) as _i2.CoinListRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Coin>>> call(
          String? currency, int? page) =>
      (super.noSuchMethod(Invocation.method(#call, [currency, page]),
          returnValue: Future<_i3.Either<_i6.Failure, List<_i7.Coin>>>.value(
              _FakeEither_1<_i6.Failure, List<_i7.Coin>>())) as _i5
          .Future<_i3.Either<_i6.Failure, List<_i7.Coin>>>);
}
